### ISSUE TITLE
LED not Working

### ISSUE THREAD

**Issue by computergeek1507** [wramsdell/TriantaduoWS2811#1]
I tried the following code and the LEDs are just blue, they never switch to red.
#include "TDWS2811.h"

TDWS2811 td;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(0, OUTPUT);
  pinMode(13, OUTPUT);
  Serial.println("Start Setup");
  td.setChannelType(0,RGB);
  Serial.printf("Setup complete!\n");
}

void loop() {
  // put your main code here, to run repeatedly:
  //Serial.printf("Active buffer = %08X\t Inactive buffer = %08X",td.getActiveBuffer(),td.getInactiveBuffer());
  digitalWrite(13, !digitalRead(13));

  color_t baseColor={0,0,255};
    color_t baseColor2={255,0,0};

   for (int i=0;i<50;i++)
  {
    td.setLed(0,i,baseColor);
  }
  delay(1000);
  for (int i=0;i<50;i++)
  {
    td.setLed(0,i,baseColor2);
  }
}

![image](https://user-images.githubusercontent.com/2293065/73601841-7f07f580-4536-11ea-9fd0-d5ee0e7d24ba.png)

**Comment by RobinB** [comment]
Try adding a delay after the second for loop.
